### ISSUE TITLE
[FEATURE REQUEST] : Modernize build system

### ISSUE THREAD

**Issue by baseplate-admin** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#419]
**Is your feature request related to a problem? Please describe.**
Hi there,
It seems that you guys use old python packaging format. It would be better should you guys move to a new build system ( eg: poetry and hatchling )

**Describe the solution you'd like**
move to `hatchling` or `poetry.core.masonry.api`

**Describe alternatives you've considered**
Keep old setuptools

**Additional context**
We can use something like 
```yaml
name: Release
on:
    release:
        types:
            - created

jobs:
    publish:
        strategy:
            fail-fast: false
            matrix:
                python-version: [3.11]
                poetry-version: [1.3.2]
                os: [ubuntu-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Run image
              uses: abatilo/actions-poetry@v2.0.0
              with:
                  poetry-version: ${{ matrix.poetry-version }}
            - name: Publish
              env:
                  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
              run: |
                  poetry config pypi-token.pypi $PYPI_TOKEN
                  poetry publish --build

```
To automate the release process and since the entire python ecosystem is moving into using poetry build backends there will be more support

<sub>CC : @cullzie  </sub>
